output:
  type: "csv"
  dir: "./results"
  filename: "example_filename"

datasets:
  dataset1:
    audio_dir: "resources/common_voice_05/wav"
    reference_dir: "resources/common_voice_05/txt"

transcribers:
#  faster_whisper:
#    asr: "faster_whisper"
#    model: "medium"
#    compute_type: "int8"
#    device: "cpu"
#    beam_size: 5
#    language: "pt"
#  whisper_1:
#    asr: "whisper"
#    model: "medium"
#    device: "cpu"
#    language: "pt"
#    fp16: False
  wav2vec:
    asr: "wav2vec"
    model: "facebook/wav2vec2-large-xlsr-53-portuguese"
    compute_type: "float32"
    device: "cpu"
  hf:
    asr: "hf"
    model: "facebook/wav2vec2-large-xlsr-53-portuguese"
    compute_type: "float32"
    device: "cpu"